PREFIX cube: <https://cube.link/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX schema: <http://schema.org/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?month ?year ?measure
WHERE {
  GRAPH <https://lindas.admin.ch/foag/agricultural-market-data> {
    FILTER (?product in ( <https://agriculture.ld.admin.ch/foag/product/142> ) )
    FILTER (?costComponent in ( <https://agriculture.ld.admin.ch/foag/cost-component/0>,<https://agriculture.ld.admin.ch/foag/cost-component/1> ) )
    FILTER (?productOrigin in ( <https://agriculture.ld.admin.ch/foag/product-origin/1> ) )
    <https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Production_Price_Month> cube:observationSet ?observationSet .
    ?observationSet cube:observation ?observation .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/cost-component> ?costComponent .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/currency> ?currency .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/data-method> ?dataMethod .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/data-source> ?dataSource .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/date> ?date .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/foreign-trade> ?foreignTrade .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/key-indicator-type> ?keyIndicatorType .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/market> ?market .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/product-group> ?productGroup .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/product-subgroup> ?productSubgroup .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/product> ?product .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/product-properties> ?productProperties .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/production-system> ?productionSystem .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/product-origin> ?productOrigin .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/sales-region> ?salesRegion .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/unit> ?unit .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/usage> ?usage .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/value-chain-detail> ?valueChainDetail .
    ?observation <https://agriculture.ld.admin.ch/foag/dimension/value-chain> ?valueChain .
    ?observation <https://agriculture.ld.admin.ch/foag/measure/price> ?measure .
  }
  ?date time:year ?year.
  ?date time:month ?month.
} ORDER BY ?year ?month
