---
title: Testseite für die Einbettung einer Datawrapper-Grafik
subtitle: Beispiel Produzentenanteil am Konsumentenfranken bei UHT-Milch
author: Damian Oswald
date: 2024-05-22
lang: de
---

:::{.callout-note}
Diese Webseite dient als Proof-of-Concept und zielt nicht darauf ab, eine offizielle Statistik für das Bundesamt für Landwirtschaft zu erstellen.
:::

Die aktuellen Milchpreise werden regelmässig vom Bundesamt für Landwirtschaft auf LINDAS hochgeladen. Mithilfe eines SPARQL-Queries werden diese Daten abgefragt, um aktuelle Marktinformationen zu erhalten. Diese Daten dienen der Berechnung des Produzentenanteils am Konsumentenpreis und werden anschliessend in einer interaktiven Grafik visualisiert. Diese Grafiken sind in diese Test-Webseite eingebettet.[^1]

[^1]: Die interaktiven Grafiken werden in die Testseite als *iframe* eingebettet, um die Ergebnisse anschaulich darzustellen. Dies ermöglicht eine dynamische Präsentation der aktuellen Daten, welche sich in allen möglichen Websites einbetten lässt.

```{=html}
<iframe title="Produzenten- und Konsumentenpreise für konventionelle Milch" aria-label="Interactive line chart" id="datawrapper-chart-BxLYR" src="https://datawrapper.dwcdn.net/BxLYR/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="464" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>
```

Der Produzentenanteil am Konsumentenfranken beschreibt den Anteil des Verkaufspreises eines Produkts -- hier von konventioneller Molkereimilch -- der direkt an den Produzenten oder Landwirt geht.

```{=html}
<iframe title="Produzentenanteil am Konsumentenfranken für Milch" aria-label="Interactive line chart" id="datawrapper-chart-hdlcx" src="https://datawrapper.dwcdn.net/hdlcx/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="392" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>

```

Der Produzentenanteil am Konsumentenfranken $R(t)$ für Milch wird wie folgt berechnet.
$$
R(t) = 100\% \frac{P_p(t)}{P_c(t)}
$$
wobei $P_p(t)$ der Produzentenpreis zum Zeitpunkt $t$ ist und $P_c(t)$ der Konsumentenpreis zum Zeitpunkt $t$. Dieser *rohe* Produzentenanteil wurde mithilfe einer saisonalen Zerlegung von Zeitreihen mit Loess (Locally Estimated Scatterplot Smoothing) in Trend, saisonale Effekte und kurzzeitige Fluktuationen zerlegt. Diese Methode ist in der R Funktion `stl` implementiert.
